version: '3.7'
services:
  api:
    image: asapp-qa-challenge-api
    container_name: backend
    ports:
      - "5000:5000"
  ui:
    image: asapp-qa-challenge-ui
    container_name: client
    ports:
      - "3000:3000"
    command: ["./run.sh"]

  cypress:
    build: ./tests
    container_name: cypress
    depends_on:
      - api
      - ui
    volumes:
      - ./tests:/tests
    command: npm run cy:run:local

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_MEMORY=512m
      - SONAR_ES_HEAP_SIZE=512m
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions

volumes:
  sonarqube_data:
  sonarqube_extensions:
